/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orgfakulteta;

import connect.javaconnect;
import java.util.LinkedList;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import klase.Katedra;
import klase.*;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author stefan
 */
public class DodajFakultet extends javax.swing.JDialog {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private static Glavni glavni = new Glavni();
    Fakultet faks;

    LinkedList<String> stavke;
    LinkedList<JComboBox> kombo;
    LinkedList<JTextField> tekst;
    LinkedList<Fakultet> fakulteti;
    LinkedList<String> faksevi;

    /**
     * Creates new form DodajFakultet
     */
    /*public DodajFakultet(java.awt.Frame parent, boolean modal) {
     super(parent, modal);
     initComponents();
       
     kombo = new LinkedList<JComboBox>();
     kombo.add(jComboBox1);
     kombo.add(jComboBox2);
     kombo.add(jComboBox3);
     kombo.add(jComboBox4);
     kombo.add(jComboBox5);
     kombo.add(jComboBox6);
     tekst = new LinkedList<JTextField>();
     tekst.add(jStavka1);
     tekst.add(jStavka2);
     tekst.add(jStavka3);
     tekst.add(jStavka4);
     tekst.add(jStavka5);
     tekst.add(jStavka6);
     fakulteti = new LinkedList<String>();
        
     }*/
    DodajFakultet(java.awt.Frame parent, boolean modal, Fakultet fakultet) {
        super(parent, false);
        initComponents();
        conn = javaconnect.ConnectDb();
        this.faks = fakultet;
//        popuniTabelu();
        popuniCombo();
        //this.stavke = st;
        //this.fakulteti = fakulteti;
        stavke = new LinkedList<>();
        kombo = new LinkedList<JComboBox>();
        tekst = new LinkedList<JTextField>();
        //tekst.add(jStavka);

        faksevi = new LinkedList<String>();
    }

//    private void popuniTabelu() {
//               try {
//            String sql = "select * from fakulteti";
//            pst = conn.prepareStatement(sql);
//            rs = pst.executeQuery();
//            jtblItem.setModel(DbUtils.resultSetToTableModel(rs));
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
//        } finally {
//            try {
//                rs.close();
//                pst.close();
//            } catch (Exception e) {
//            }
//        }
//    }
    private void popuniCombo() {
        try {
            String sql = "select * from fakulteti";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String fakultet = rs.getString("Fakultet");
                jComboFakulteti.addItem(fakultet);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblItem = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbtnDodajNovi = new javax.swing.JButton();
        jbtnIzmeni = new javax.swing.JButton();
        jbtnObrisi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtAdresa = new javax.swing.JTextField();
        jtxtNaziv = new javax.swing.JTextField();
        jtxtTelefon = new javax.swing.JTextField();
        jtxtDekan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtxtSearch = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jComboFakulteti = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblItem);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(" "));

        jbtnDodajNovi.setText("Unos novog");
        jbtnDodajNovi.setToolTipText("Unesite novi fakultet");
        jbtnDodajNovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajNoviActionPerformed(evt);
            }
        });

        jbtnIzmeni.setText("Izmenite");
        jbtnIzmeni.setToolTipText("Izmenite selektovana polja");
        jbtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniActionPerformed(evt);
            }
        });

        jbtnObrisi.setText("Obrisite");
        jbtnObrisi.setToolTipText("Obrisite selektovana polja");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        jButton2.setText("Obrisite polja");
        jButton2.setToolTipText("Obrisite selektovana polja");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnDodajNovi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnDodajNovi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnObrisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Izvrsite izmenu:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 102))); // NOI18N

        jLabel7.setText("Dekan");

        jLabel8.setText("Adresa");

        jtxtAdresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAdresaActionPerformed(evt);
            }
        });

        jtxtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNazivActionPerformed(evt);
            }
        });

        jLabel9.setText("Telefon");

        jLabel6.setText("Fakultet");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32)
                        .addComponent(jtxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDekan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDekan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pronadjite fakultet:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 51))); // NOI18N

        jtxtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSearchActionPerformed(evt);
            }
        });
        jtxtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Odaberite fakultet:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 51))); // NOI18N

        jComboFakulteti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboFakulteti.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboFakultetiItemStateChanged(evt);
            }
        });
        jComboFakulteti.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboFakultetiPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboFakulteti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboFakultetiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboFakulteti, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboFakulteti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kreirajte organizacionu strukturu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel5.setToolTipText("Kreirajte organizacionu strukturu");

        jButton1.setText("Kreiraj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtAdresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAdresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAdresaActionPerformed

    private void jtblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblItemMouseClicked
        //        try {
        //            int row = jtblItem.getSelectedRow();
        //            String klik = (jtblItem.getModel().getValueAt(row, 0).toString());
        //            String sql = "select * from fakulteti where Naziv ='" + klik + "'";
        //            pst = conn.prepareStatement(sql);
        //            rs = pst.executeQuery();
        //            if (rs.next()) {
        //                String dodaj1 = rs.getString("Naziv");
        //                jtxtNaziv.setText(dodaj1);
        //                String dodaj2 = rs.getString("Dekan");
        //                jtxtDekan.setText(dodaj2);
        //                String dodaj3 = rs.getString("Adresa");
        //                jtxtAdresa.setText(dodaj3);
        //                String dodaj4 = rs.getString("Telefon");
        //                jtxtTelefon.setText(dodaj4);
        //            }
        //        } catch (Exception e) {
        //            JOptionPane.showMessageDialog(null, e);
        //        }finally {
        //            try {
        //                rs.close();
        //                pst.close();
        //            } catch (Exception e) {
        //            }
        //        }
    }//GEN-LAST:event_jtblItemMouseClicked

    private void jComboFakultetiPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboFakultetiPopupMenuWillBecomeInvisible
        String item = (String) jComboFakulteti.getSelectedItem();
        String sql = "select * from fakulteti where Fakultet =?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, item);
            rs = pst.executeQuery();
            if (rs.next()) {
                String dodaj1 = rs.getString("Fakultet");
                jtxtNaziv.setText(dodaj1);
                String dodaj2 = rs.getString("Dekan");
                jtxtDekan.setText(dodaj2);
                String dodaj3 = rs.getString("Adresa");
                jtxtAdresa.setText(dodaj3);
                String dodaj4 = rs.getString("Telefon");
                jtxtTelefon.setText(dodaj4);
            }
            pst = conn.prepareStatement(sql);
            pst.setString(1, item);
            rs = pst.executeQuery();
            jtblItem.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboFakultetiPopupMenuWillBecomeInvisible

    private void jComboFakultetiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboFakultetiItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboFakultetiItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        organizacionaStruktura org = new organizacionaStruktura(glavni, true);
        org.setVisible(true);
        //for (int i = 0; i < fakulteti.size(); i++) {
        // fakulteti.add(new Fakultet(jStavka.getText()));
//        faks.setIme(jStavka1.getText());
        //}
//        for (int i = 0; i < kombo.size(); i++) {
//            //System.out.println(tekst.get(i).getText());
//            //stavke.add(tekst.get(i).getText());
//            switch (kombo.get(i).getSelectedItem().toString()) {
//                case "Katedra":
//                    faks.dodajKatedru(new Katedra(tekst.get(i).getText()));
//                    break;
//                case "Laboratorija":
//                    faks.dodajLabCentar(new LaboratorijaCentar(tekst.get(i).getText()));
//                    break;
//                case "Centar":
//                    faks.dodajLabCentar(new LaboratorijaCentar(tekst.get(i).getText()));
//                    break;
//                case "Sluzba":
//                    faks.dodajSluzbu(new Sluzba(tekst.get(i).getText()));
//                    break;
//                case "Upravni organ":
//                    faks.dodajUpravu(new Uprava(tekst.get(i).getText()));
//                    break;
//                case "Ostalo":
//                    faks.dodajOstalo(new Ostalo(tekst.get(i).getText()));
//                    break;
//            }
//
//        }
//        //glavni.prikaziFakultete(fakulteti);
//        glavni.populateTree(stavke);
        // glavni.osvezi();
        //        if (EventQueue.isDispatchThread()) {
        //            swingTask.run();
        //        } else {
        //            try{
        //            EventQueue.invokeAndWait(swingTask);
        //            }catch (Exception e){
        //
        //            }
        //        }
        // glavni.populateTree(stavke);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnDodajNoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajNoviActionPerformed
        try {
            String sql = "Insert into fakulteti (Fakultet,Dekan,Adresa,Telefon) values (?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, jtxtNaziv.getText());
            pst.setString(2, jtxtDekan.getText());
            pst.setString(3, jtxtAdresa.getText());
            pst.setString(4, jtxtTelefon.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Uspesno ste snimili!");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
        jComboFakulteti.removeAllItems();
        popuniCombo();
        //        finally {
        //            try {
        //                rs.close();
        //                pst.close();
        //            } catch (Exception e) {
        //            }
        //        }
    }//GEN-LAST:event_jbtnDodajNoviActionPerformed

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Da li zelite da obrisete fakultet?","Brisanje",JOptionPane.YES_NO_OPTION);
        if(p==0){
        String sql = "delete from fakulteti where Fakultet=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, jtxtNaziv.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Uspesno ste obrisali fakultet!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        jComboFakulteti.removeAllItems();
        popuniCombo();
        }
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    private void jbtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniActionPerformed
        try {
            String naziv = jtxtNaziv.getText();
            String dekan = jtxtDekan.getText();
            String adresa = jtxtAdresa.getText();
            String telefon = jtxtTelefon.getText();
            String sql = "update fakulteti set Fakultet='" + naziv + "',Dekan='" + dekan + "',Adresa='" + adresa + "',Telefon='" + telefon + "'where Fakultet='" + naziv + "'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Uspesno ste izvrsini izmenu!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        jComboFakulteti.removeAllItems();
        popuniCombo();
        jtblItem.removeAll();
//        popuniTabelu();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnIzmeniActionPerformed

    private void jtxtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSearchKeyReleased
        try {
            String sql = "select * from fakulteti where Fakultet=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, jtxtSearch.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                String dodaj1 = rs.getString("Fakultet");
                jtxtNaziv.setText(dodaj1);
                String dodaj2 = rs.getString("Dekan");
                jtxtDekan.setText(dodaj2);
                String dodaj3 = rs.getString("Adresa");
                jtxtAdresa.setText(dodaj3);
                String dodaj4 = rs.getString("Telefon");
                jtxtTelefon.setText(dodaj4);
            }
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           jtxtNaziv.setText("");
           jtxtDekan.setText("");
           jtxtAdresa.setText("");
           jtxtTelefon.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtxtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSearchActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchActionPerformed

    private void jComboFakultetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboFakultetiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboFakultetiActionPerformed

    private void jtxtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNazivActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboFakulteti;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtnDodajNovi;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JTable jtblItem;
    private javax.swing.JTextField jtxtAdresa;
    private javax.swing.JTextField jtxtDekan;
    private javax.swing.JTextField jtxtNaziv;
    private javax.swing.JTextField jtxtSearch;
    private javax.swing.JTextField jtxtTelefon;
    // End of variables declaration//GEN-END:variables

}
